"""baseline schema

Revision ID: 2dc6158c48d9
Revises: 
Create Date: 2026-09-18 09:59:23.710273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc6158c48d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('work_items',
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PIPELINE_STAGE', 'DOMAIN_EVENT', name='workitemkind', native_enum=False, length=16), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='workitemstate', native_enum=False, length=16), nullable=False),
    sa.Column('payload_reference', sa.String(length=512), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('work_item_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='agentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'summarized', 'retained', name='conversationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('summarized_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('knowledge_elements',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.Enum('CONCEPT', 'THEME', 'METHOD', 'CLAIM', 'RELATIONSHIP', name='knowledgeelementtype', native_enum=False, length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', name='knowledgeelementstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Enum('SYSTEM', 'USER', name='createdby', native_enum=False, length=16), nullable=False),
    sa.Column('superseded_element_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['superseded_element_id'], ['knowledge_elements.element_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('memory_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('objective', 'hypothesis', 'method', 'decision', 'terminology', 'guidance', 'style', 'other', name='memoryrecordtype', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('current', 'superseded', name='memoryrecordstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Enum('system', 'user', name='createdby', native_enum=False, length=16), nullable=False),
    sa.Column('superseded_record_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['superseded_record_id'], ['memory_records.record_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='projectstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('writing_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='writingprofilestatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('uq_writing_profile_one_active_per_agent', 'writing_profiles', ['agent_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', name='knowledgeelementstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['knowledge_elements.element_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('user_request', 'system_response', name='messagedirection', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_message_conversation_sequence')
    )
    op.create_table('profile_characteristics',
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_type', sa.Enum('structure', 'vocabulary', 'transitions', 'explanation', 'citation', name='profilecharacteristictype', native_enum=False, length=16), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['writing_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('characteristic_id')
    )
    op.create_table('research_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('content_reference', sa.String(length=512), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentprocessingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('purpose', sa.Enum('RESEARCH', 'WRITING_STYLE_SAMPLE', name='documentpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('chunk_evidence_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Enum('SYSTEM', 'USER', name='createdby', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.document_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('chunk_id', 'document_id', name='uq_chunk_evidence_link_chunk_document')
    )
    op.create_table('knowledge_chunk_embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.chunk_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('memory_provenance_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('user_input', 'conversation', 'knowledge_element', 'document', name='memoryprovenancesourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(source_type = 'user_input' AND conversation_id IS NULL AND element_id IS NULL AND document_id IS NULL) OR (source_type = 'conversation' AND conversation_id IS NOT NULL AND element_id IS NULL AND document_id IS NULL) OR (source_type = 'knowledge_element' AND element_id IS NOT NULL AND conversation_id IS NULL AND document_id IS NULL) OR (source_type = 'document' AND document_id IS NOT NULL AND conversation_id IS NULL AND element_id IS NULL)", name='ck_memory_provenance_link_exclusive_target'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.document_id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['knowledge_elements.element_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['memory_records.record_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('message_context_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('research_document', 'knowledge_element', 'knowledge_chunk', 'memory_record', name='messagecontexttargettype', native_enum=False, length=32), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('memory_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(target_type = 'research_document' AND document_id IS NOT NULL AND element_id IS NULL AND chunk_id IS NULL AND memory_record_id IS NULL) OR (target_type = 'knowledge_element' AND element_id IS NOT NULL AND document_id IS NULL AND chunk_id IS NULL AND memory_record_id IS NULL) OR (target_type = 'knowledge_chunk' AND chunk_id IS NOT NULL AND document_id IS NULL AND element_id IS NULL AND memory_record_id IS NULL) OR (target_type = 'memory_record' AND memory_record_id IS NOT NULL AND document_id IS NULL AND element_id IS NULL AND chunk_id IS NULL)", name='ck_message_context_link_exclusive_target'),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.document_id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['knowledge_elements.element_id'], ),
    sa.ForeignKeyConstraint(['memory_record_id'], ['memory_records.record_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('profile_characteristic_sources',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['profile_characteristics.characteristic_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.document_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('characteristic_id', 'document_id', name='uq_profile_characteristic_source')
    )
    # ### end Alembic commands ###

    # ADR-005 Decision 1's lexical retrieval branch - not representable via Alembic's ORM-level
    # op.* commands (an FTS5 virtual table on SQLite; a generated tsvector column + GIN index on
    # Postgres), so raw DDL per dialect. Mirrors app.database.session.init_db's own SQLite-only
    # FTS5 creation, kept for fast ephemeral test/dev databases that bootstrap via create_all()
    # instead of a real migration - the two are deliberately parallel, not DRY against each
    # other, matching how create_all() and Alembic already coexist for different purposes here.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute("CREATE VIRTUAL TABLE IF NOT EXISTS knowledge_chunk_fts USING fts5(content, agent_id UNINDEXED)")
    elif bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE knowledge_chunks ADD COLUMN search_vector tsvector "
            "GENERATED ALWAYS AS (to_tsvector('english', content)) STORED"
        )
        op.execute("CREATE INDEX knowledge_chunks_search_vector_idx ON knowledge_chunks USING GIN (search_vector)")


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute("DROP TABLE IF EXISTS knowledge_chunk_fts")
    elif bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS knowledge_chunks_search_vector_idx")
        op.execute("ALTER TABLE knowledge_chunks DROP COLUMN IF EXISTS search_vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_characteristic_sources')
    op.drop_table('message_context_links')
    op.drop_table('memory_provenance_links')
    op.drop_table('knowledge_chunk_embeddings')
    op.drop_table('chunk_evidence_links')
    op.drop_table('research_documents')
    op.drop_table('profile_characteristics')
    op.drop_table('messages')
    op.drop_table('knowledge_chunks')
    op.drop_index('uq_writing_profile_one_active_per_agent', table_name='writing_profiles', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_table('writing_profiles')
    op.drop_table('projects')
    op.drop_table('memory_records')
    op.drop_table('knowledge_elements')
    op.drop_table('conversations')
    op.drop_table('sessions')
    op.drop_table('agents')
    op.drop_table('work_items')
    op.drop_table('users')
    # ### end Alembic commands ###
