"""add rate limit counters table

Revision ID: 4d323d592976
Revises: e3b0a1ae4624
Create Date: 2026-09-21 15:24:15.717438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d323d592976'
down_revision: Union[str, Sequence[str], None] = 'e3b0a1ae4624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate always proposes dropping the knowledge_chunk_fts* shadow tables here -
    # a known false positive since they're raw-SQL-created (FTS5 virtual table), never part of
    # SQLAlchemy metadata. Stripped, same as every prior migration in this project.
    op.create_table('rate_limit_counters',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
