"""add indexes on high traffic query columns

Revision ID: e3b0a1ae4624
Revises: 3c841981a6d4
Create Date: 2026-09-21 12:56:59.004952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b0a1ae4624'
down_revision: Union[str, Sequence[str], None] = '3c841981a6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate always proposes dropping the knowledge_chunk_fts* shadow tables here -
    # a known false positive since they're raw-SQL-created (FTS5 virtual table), never part of
    # SQLAlchemy metadata. Stripped, same as every prior migration in this project.
    op.create_index('ix_chunk_evidence_links_document_id', 'chunk_evidence_links', ['document_id'], unique=False)
    op.create_index('ix_conversations_agent_id_deleted_at', 'conversations', ['agent_id', 'deleted_at'], unique=False)
    op.create_index('ix_knowledge_chunks_agent_id_status', 'knowledge_chunks', ['agent_id', 'status'], unique=False)
    op.create_index('ix_memory_provenance_links_record_id', 'memory_provenance_links', ['record_id'], unique=False)
    op.create_index('ix_memory_records_agent_id_status', 'memory_records', ['agent_id', 'status'], unique=False)
    op.create_index('ix_message_context_links_message_id', 'message_context_links', ['message_id'], unique=False)
    op.create_index('ix_profile_characteristics_profile_id', 'profile_characteristics', ['profile_id'], unique=False)
    op.create_index('ix_research_documents_project_id', 'research_documents', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_documents_project_id', table_name='research_documents')
    op.drop_index('ix_profile_characteristics_profile_id', table_name='profile_characteristics')
    op.drop_index('ix_message_context_links_message_id', table_name='message_context_links')
    op.drop_index('ix_memory_records_agent_id_status', table_name='memory_records')
    op.drop_index('ix_memory_provenance_links_record_id', table_name='memory_provenance_links')
    op.drop_index('ix_knowledge_chunks_agent_id_status', table_name='knowledge_chunks')
    op.drop_index('ix_conversations_agent_id_deleted_at', table_name='conversations')
    op.drop_index('ix_chunk_evidence_links_document_id', table_name='chunk_evidence_links')
    # ### end Alembic commands ###
